development:
  adapter: postgresql
  database: postgres
  username: "postgres"
  password: 'feelink-pass'
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: postgres
  password: 'feelink-pass'
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: postgres
  password: 'feelink-pass'
  pool: 5
  timeout: 5000